### ISSUE TITLE
 Issue with `user_following` Method: Incorrect Endpoint and Empty Response

### ISSUE THREAD

**Issue by antek-eth** [datarise-org-ma/twitter-client-py#1]
#### Problem:
The `user_following` method in the `TwitterClient` class does not return the expected data and instead gives an empty response with the message "Following for user id = userid not found." The issue seems to stem from using an incorrect endpoint in the library.

#### Steps to Reproduce:
1. Use the `TwitterClient` class from the library.
2. Call the `user_following` method with a valid `user_id` or `username`.
3. Observe that the response contains an error message indicating that no following data is found.

```python
from os import getenv
import json
from twitter_client_py import TwitterClient

api_key = 'APIHERE'

client = TwitterClient(api_key=api_key, timeout=20, verbose=True)

# Get user details by username
user_following = client.user_following(user_id='USERIDHERE')
if user_following.status_code == 200:
    print(json.dumps(user_following.json(), indent=4))
else:
    print(f"Failed to fetch following list: {user_following.status_code}")
```

#### Observed Output:
```json
{
    "detail": "Following for user id = userid not found"
}
```

#### Expected Output:
A JSON response with the list of users the specified user is following.

#### Additional Information:
When using the `requests` library directly with the endpoint `https://twitter-api45.p.rapidapi.com/following.php`, the correct response is returned:

```python
import requests

url = "https://twitter-api45.p.rapidapi.com/following.php"
querystring = {"screenname": "USERNAME"}
headers = {
    "x-rapidapi-key": "API_KEY",
    "x-rapidapi-host": "twitter-api45.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)
print(response.json())
```

This script returns the expected data.

### Proposed Solution:
Update the `user_following` method to use the correct endpoint and parameters that match the working example with the `requests` library.

#### Modified `user_following` Method:
```python
def user_following(
        self,
        username: Optional[str] = None,
        user_id: Optional[str] = None,
        limit=20,
        cursor=None,
    ) -> requests.Response:
        """
        Get users followed by a user using the Twitter/X API via RapidAPI.

        Args:
            username (str): The username of the user. Default is None.
            user_id (str): The ID of the user. Default is None.
            limit (int): The limit of users to return. Default is 20.
            cursor (str): The cursor for pagination. Default is None.

        Returns:
            requests.Response: The response from the API.
        """

        if not username and not user_id:
            raise ValueError("Either username or user_id must be provided.")

        # Use the correct endpoint
        url = "https://twitter-api45.p.rapidapi.com/following.php"
        
        params = {
            "limit": limit,
        }
        if username:
            params["screenname"] = username
            LOGGER.info(
                f"[User Following] Username: {username} - Limit: {limit}",
                extra={"limit": self.rate_limit.remaining},
            )
        if user_id:
            params["userid"] = user_id
            LOGGER.info(
                f"[User Following] User ID: {user_id} - Limit: {limit}",
                extra={"limit": self.rate_limit.remaining},
            )
        if cursor:
            params["cursor"] = cursor

        headers = {
            "x-rapidapi-key": self.__api_key,
            "x-rapidapi-host": "twitter-api45.p.rapidapi.com"
        }

        with self.__session.get(
            url, params=params, headers=headers, timeout=self.timeout
        ) as response:
            if response.status_code == 200:
                self.rate_limit = RateLimit.from_headers(response.headers)
            LOGGER.debug(
                f"[User Following] Response: {response.status_code}, elapsed time: {response.elapsed.total_seconds()}",
                extra={"limit": self.rate_limit.remaining},
            )
            return response
```

#### Expected Outcome:
This change should ensure that the `user_following` method returns the correct following data for a given user.

**Comment by omarmhaimdat** [comment]
Thank you for your detailed report.

After reviewing the issue, it appears that the problem is with the API itself rather than the library. The `user_following` method in the `TwitterClient` class is using the correct endpoint and parameters as intended.

Details:

- The error message "Following for user id = userid not found" indicates that the API response is returning no data for the provided user_id or username.

- When using the requests library directly with the endpoint https://twitter-api45.p.rapidapi.com/following.php, you mentioned receiving the correct response. This discrepancy suggests that you are using this [api](https://rapidapi.com/alexanderxbx/api/twitter-api45) which is different from this one [api](https://rapidapi.com/datarise-datarise-default/api/twitter-x)
